### ISSUE TITLE
Buscar en la api apache Poi si hay un método para omitir la primera fila (identificadores)

### ISSUE THREAD

**Issue by DavidGG1983** [Arquisoft/citizensLoader1b#7]

**Comment by sergupe** [comment]
Estoy buscando acerca de ello. Por lo que encuentro en internet dicen que con getRowNum(), para obtener el numero de la fila en la que estás. Luego se hace la comprobación y se omiten. ¿Probaste eso? para en caso de que así no sea seguir buscando.
